Update ci.yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -2,7 +2,7 @@ name: CI-Pipeline
 
 on:
   push:
-    branches: [ dev, main ]
+    branches: [ main ]
   pull_request:
     branches: [ main ]
 
@@ -90,10 +90,7 @@ jobs:
       - name: Run inference sanity
         run: |
           echo "🔍 Running inference sanity test..."
-          python scripts/inference.py \
-            --model_uri models:/iris_best_model/Production \
-            --eval_csv gs://mlops-474118-artifacts/data/processed/eval.csv \
-            || { echo "❌ Inference sanity test failed."; exit 1; }
+          python scripts/inference.py || { echo "❌ Inference sanity test failed."; exit 1; }
           echo "✅ Inference sanity test completed."
 
       # ---------------------------
